# Generated by Django 3.1.5 on 2021-04-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0002_pg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pg',
        ),
    ]
