# Generated by Django 3.1.5 on 2021-04-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0003_delete_pg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pg',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500)),
                ('type_pg', models.CharField(choices=[('girls', 'girls'), ('boys', 'boys'), ('both', 'both')], default='both', max_length=50)),
                ('description', models.TextField()),
                ('distance', models.CharField(default='', max_length=1000)),
                ('video', models.URLField()),
                ('verified', models.BooleanField()),
                ('services', models.TextField()),
                ('price', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('ratings', models.IntegerField()),
                ('location', models.CharField(default='', max_length=1000)),
                ('room_sharing', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
