# Generated by Django 3.1.5 on 2021-04-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0004_pg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pg',
            name='room_sharing',
        ),
        migrations.RemoveField(
            model_name='pg',
            name='services',
        ),
    ]
