# Generated by Django 3.1.5 on 2021-04-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0005_auto_20210424_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='rules',
            field=models.TextField(default=' '),
        ),
    ]
