# Generated by Django 3.1.5 on 2021-04-25 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0006_pg_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgae', models.ImageField(upload_to='images_pg/')),
                ('pg', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pg.pg')),
            ],
        ),
    ]
