# Generated by Django 3.1.5 on 2021-04-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0007_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg',
            name='video',
            field=models.CharField(default='', max_length=500),
        ),
    ]
