# Generated by Django 3.1.5 on 2021-04-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0008_auto_20210425_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg',
            name='type_pg',
            field=models.CharField(choices=[('Girls', 'girls'), ('Boys', 'boys'), ('Both', 'both')], default='both', max_length=50),
        ),
    ]
