# Generated by Django 3.1.5 on 2021-04-28 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0010_auto_20210428_0816'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
