# Generated by Django 3.1.5 on 2021-04-28 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pg', '0011_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default=' ', max_length=40)),
                ('last_name', models.CharField(default=' ', max_length=40)),
                ('email', models.CharField(default=' ', max_length=50)),
                ('address', models.CharField(default=' ', max_length=500)),
                ('phone_number', models.BigIntegerField()),
                ('state', models.CharField(default=' ', max_length=40)),
                ('zip', models.IntegerField()),
                ('college', models.CharField(default=' ', max_length=200)),
                ('order_confirmed', models.BooleanField()),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg.pg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
