# Generated by Django 3.1.5 on 2021-05-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0013_auto_20210428_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterPg',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=' ', max_length=80)),
                ('location', models.CharField(default=' ', max_length=40)),
                ('typepg', models.CharField(choices=[('Girls', 'girls'), ('Boys', 'boys'), ('Both', 'both')], default='Both', max_length=20)),
                ('phonenumber', models.BigIntegerField()),
                ('description', models.TextField()),
                ('owner_name', models.CharField(default=' ', max_length=50)),
                ('verified', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='pg',
            name='type_pg',
            field=models.CharField(choices=[('Girls', 'girls'), ('Boys', 'boys'), ('Both', 'both')], default='Both', max_length=50),
        ),
    ]
