# Generated by Django 3.2 on 2021-05-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0014_auto_20210502_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='recommended',
            field=models.BooleanField(default=0),
        ),
    ]
