# Generated by Django 3.2 on 2021-06-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0017_testmotional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='order_confirmed',
        ),
        migrations.AddField(
            model_name='booking',
            name='order_id',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='booking',
            name='order_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_order_id',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_payment_id',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_signature',
            field=models.CharField(default=' ', max_length=450),
        ),
    ]
