# Generated by Django 3.2 on 2021-06-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0018_auto_20210610_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='expiry_date',
            field=models.CharField(default='', max_length=30),
        ),
    ]
