# Generated by Django 3.2 on 2021-06-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0019_auto_20210615_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='slug',
            field=models.SlugField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='pg',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
